# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=255),
        ),
    ]
