# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womai', '0002_auto_20190110_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('headImg', models.CharField(max_length=100)),
                ('bgcolor', models.CharField(max_length=20)),
                ('opicaty', models.IntegerField()),
            ],
        ),
    ]
