# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womai', '0005_shoplist_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoplist',
        ),
    ]
