# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womai', '0006_delete_shoplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sip', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('headImg', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=5)),
                ('zoom', models.CharField(max_length=255)),
                ('small', models.CharField(max_length=255)),
            ],
        ),
    ]
