# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womai', '0007_shoplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emph',
            new_name='email',
        ),
    ]
