# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womai', '0008_auto_20190115_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
