# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womai', '0009_auto_20190115_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
